M48
; DRILL file {KiCad 9.0.7} date 2026-05-12T18:13:15-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-12T18:13:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X36.14Y-79.21
X36.14Y-84.99
T2
X59.45Y-58.6
X66.25Y-58.6
X75.7Y-58.6
X82.5Y-58.6
T3
X33.5Y-101.5
X34.25Y-63.25
X84.5Y-101.5
X93.75Y-63.25
M30
